services:
  # ollama:
  #   volumes:
  #     - $HOME/.ollama:/root/.ollama
  #   # container_name: ollama
  #   # pull_policy: always
  #   tty: true
  #   restart: unless-stopped
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  #   ports:
  #     - ${OLLAMA_PORT-11435}:11434
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   profiles:
  #     - ollama
  #     - all

  open-webui:
    # Default tag is usually main
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main} 
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    #depends_on:
    #  - ollama
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
#    environment:
#      - 'OLLAMA_BASE_URL=http://ollama:11434'
#      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
    profiles:
      - ui
      - all
      - ""
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8090:8080"
    volumes:
      - ./searxng:/etc/searxng
    restart: always
    profiles: 
      - search
      - all

volumes:
  ollama: {}
  open-webui: {}

