services:
  #  ollama:
  #  volumes:
  #    - ollama:/root/.ollama
  #  container_name: ollama
  #  pull_policy: always
  #  tty: true
  #  restart: unless-stopped
  #  image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    #build:
    # context: .
        #    args:
        # OLLAMA_BASE_URL: '/ollama'
        #dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    #depends_on:
    #  - ollama
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    environment:
#      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    ports:
    - 8082:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
  # weaviate-console:
  #   image: semitechnologies/weaviate-console:latest #1.13.6
  #   ports:
  #     - 8084:80
  #   WEAVIATE: GUI: https://github.com/weaviate/Verba
  verba:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_URL_VERBA="http://weaviate:8080"
    #   - OLLAMA_URL=http://localhost:11434 
    # - OLLAMA_MODEL:llama3.2


volumes:
  # ollama: {}
  open-webui: {}
  weaviate_data: {}
