services:
  # ollama:
  #   volumes:
  #     - $HOME/.ollama:/root/.ollama
  #   container_name: ollama
  #   # pull_policy: always
  #   tty: true
  #   restart: unless-stopped
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  #   ports:
  #     - ${OLLAMA_PORT-7869}:11434
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    ports:
    - 8082:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      OPENAI_APIKEY: $OPENAI_API_KEY
      COHERE_APIKEY: $COHERE_API_KEY
      ENABLE_MODULES: 'e'
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  # weaviate-console:
  #   image: semitechnologies/weaviate-console:latest #1.13.6
  #   ports:
  #     - 8084:80
  #   WEAVIATE: GUI: https://github.com/weaviate/Verba
  verba:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - weaviate

    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - WEAVIATE_URL_VERBA="http://weaviate:8080"
      # - OLLAMA_URL="http://ollama:7869"
      - OLLAMA_URL=host.docker.internal:11434    #   - OLLAMA_URL=http://localhost:11434 
      - OLLAMA_MODEL:llama3.2
      - OLLAMA_EMBED_MODEL:nomic-embed-text
      # - OPENAI_API_KEY=$OPENAI_API_KEY
      # - COHERE_API_KEY=$COHERE_API_KEY
      # - OLLAMA_URL=http://host.docker.internal:11434
      # - OLLAMA_MODEL=$OLLAMA_MODEL
      # - OLLAMA_EMBED_MODEL=$OLLAMA_EMBED_MODEL
      # - UNSTRUCTURED_API_KEY=$UNSTRUCTURED_API_KEY
      # - UNSTRUCTURED_API_URL=$UNSTRUCTURED_API_URL
      # - GITHUB_TOKEN=$GITHUB_TOKEN
    ports:
      - 8083:8000
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  weaviate_data: {}
