services:
  stable-diffusion-webui:
    # runtime: amd
    # image: automatic111/stable-diffusion-webui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860"
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - models:/app/stable-diffusion-webui/models

    command: python3 launch.py --listen
    devices:
      - /dev/dri
      - /dev/kfd

volumes:
  models: {}